version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: episense-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: episense_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - episense-network

volumes:
  mongodb_data:
    driver: local

networks:
  episense-network:
    driver: bridge