#!/bin/bash

# Wrapper script para definir variáveis de ambiente no formato correto

export HOST="${HOST:-0.0.0.0}"
export PORT="${PORT:-8081}"

# ScyllaDB
export SCYLLA_NODES="${SCYLLA_NODES}"
export SCYLLA_KEYSPACE="${SCYLLA_KEYSPACE}"

# Backend
export BACKEND_URL="${BACKEND_URL}"
export BACKEND_TIMEOUT_SECS="${BACKEND_TIMEOUT_SECS:-30}"
export BACKEND_MAX_RETRIES="${BACKEND_MAX_RETRIES:-3}"
export BACKEND_INITIAL_BACKOFF_MS="${BACKEND_INITIAL_BACKOFF_MS:-100}"
export BACKEND_MAX_BACKOFF_MS="${BACKEND_MAX_BACKOFF_MS:-60000}"

# Retry Worker
export RETRY_WORKER_INTERVAL_SECS="${RETRY_WORKER_INTERVAL_SECS:-60}"
export RETRY_WORKER_BATCH_SIZE="${RETRY_WORKER_BATCH_SIZE:-100}"

# Performance
export PERFORMANCE_HTTP_WORKERS="${PERFORMANCE_HTTP_WORKERS:-4}"
export PERFORMANCE_MAX_CONNECTIONS="${PERFORMANCE_MAX_CONNECTIONS:-256}"
export PERFORMANCE_KEEP_ALIVE_SECS="${PERFORMANCE_KEEP_ALIVE_SECS:-75}"

# Executar a aplicação
exec ./fhir-server "$@"
