replicaCount: 1

image:
  repository: ghcr.io/your-org/episense-api
  tag: "0.1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources: {}

ingress:
  enabled: false
  className: ""
  hosts: []
  tls: []
