apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "episense.fullname" . }}
  labels:
    {{- include "episense.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "episense.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "episense.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          livenessProbe:
            httpGet:
              path: /health
              port: http
