spring:
  application:
    name: fhir-generator
  cassandra:
    keyspace-name: episense
    contact-points: localhost
    port: 9042
    local-datacenter: datacenter1
    schema-action: create_if_not_exists

server:
  port: 8080

external:
  api:
    url: http://localhost:5000/api/ingestion/fhir
    timeout: 30000

scheduler:
  enabled: true
  initial-delay: 60000
  min-interval-minutes: 3
  max-interval-minutes: 10
  min-batch-size: 20
  max-batch-size: 100

logging:
  level:
    root: INFO
    com.episense.fhirgenerator: DEBUG
    com.datastax.oss.driver: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
