// <auto-generated />
using System;
using System.Collections.Generic;
using EpiSense.Analysis.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EpiSense.Analysis.Migrations
{
    [DbContext(typeof(AnalysisDbContext))]
    [Migration("20251022214031_RemoveProcessedAtAndRawDataId")]
    partial class RemoveProcessedAtAndRawDataId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EpiSense.Analysis.Domain.Entities.AnalysisResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnalysisType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CasesCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double>("RiskScore")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisType");

                    b.HasIndex("AnalyzedAt");

                    b.HasIndex("Region");

                    b.ToTable("analysis_results", "analysis");
                });

            modelBuilder.Entity("EpiSense.Analysis.Domain.Entities.ObservationSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodigoMunicipioIBGE")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("codigo_municipio_ibge");

                    b.Property<DateTime>("DataColeta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_coleta");

                    b.Property<List<string>>("Flags")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("flags");

                    b.Property<Dictionary<string, decimal>>("LabValues")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("lab_values");

                    b.Property<string>("ObservationId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("observation_id");

                    b.HasKey("Id");

                    b.HasIndex("CodigoMunicipioIBGE");

                    b.HasIndex("DataColeta");

                    b.HasIndex("Flags");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Flags"), "gin");

                    b.ToTable("observation_summaries", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
